{application,ueberauth_github,
             [{optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger,ueberauth,oauth2]},
              {description,"ueberauth_github"},
              {modules,['Elixir.Ueberauth.Strategy.Github',
                        'Elixir.Ueberauth.Strategy.Github.OAuth',
                        'Elixir.UeberauthGithub']},
              {registered,[]},
              {vsn,"0.8.2"}]}.
